In [8]:
import numpy as np
import random as rd
x = np.arange(0,30,4)
y = np.array([[1,2,3],[4,5,6]])
print(x)
print(y)

[ 0  4  8 12 16 20 24 28]
[[1 2 3]
 [4 5 6]]


In [17]:
o = np.linspace(2,6,9)
print(o)
print(o.shape)
print(o.reshape(3,3))
#print(o.resize(3,3))

[2.  2.5 3.  3.5 4.  4.5 5.  5.5 6. ]
(9,)
[[2.  2.5 3. ]
 [3.5 4.  4.5]
 [5.  5.5 6. ]]


In [21]:
np.ones((2,2),int)

array([[1., 1.],
       [1., 1.]])

In [22]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.diag(y)

array([1, 5])

In [27]:
np.diag(x)

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 12,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 16,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 20,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 24,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 28]])

In [29]:
a = np.linspace(2,10,35)
a

array([ 2.        ,  2.23529412,  2.47058824,  2.70588235,  2.94117647,
        3.17647059,  3.41176471,  3.64705882,  3.88235294,  4.11764706,
        4.35294118,  4.58823529,  4.82352941,  5.05882353,  5.29411765,
        5.52941176,  5.76470588,  6.        ,  6.23529412,  6.47058824,
        6.70588235,  6.94117647,  7.17647059,  7.41176471,  7.64705882,
        7.88235294,  8.11764706,  8.35294118,  8.58823529,  8.82352941,
        9.05882353,  9.29411765,  9.52941176,  9.76470588, 10.        ])

In [34]:
import random as rd
rd.shuffle(a)
a

array([ 6.94117647,  4.11764706,  3.41176471,  6.23529412,  7.41176471,
        2.94117647,  5.76470588,  8.58823529,  7.88235294,  4.58823529,
        9.29411765,  4.35294118,  2.23529412,  8.35294118,  6.70588235,
        5.05882353,  3.88235294,  5.29411765,  8.82352941,  9.52941176,
        3.64705882,  6.47058824,  9.05882353,  8.11764706,  6.        ,
        4.82352941,  9.76470588, 10.        ,  2.        ,  7.17647059,
        5.52941176,  2.47058824,  2.70588235,  7.64705882,  3.17647059])

In [39]:
np.min(a),np.max(a),np.sum(a),np.mean(a),np.std(a)

(2.0, 10.0, 210.00000000000003, 6.000000000000001, 2.3763541031440183)

In [40]:
a.argmax(),a.argmin()

(27, 28)

In [47]:
b = np.arange(36)            # see the diff bw reshape and resize
c =b.reshape(6,6)               # dont change the original array make only copy of that and can be stored in other variable
print(b)
print(c)
b.resize(6,6)
b

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [48]:
b[2,2]

14

In [51]:
b[2,3:]

array([15, 16, 17])

In [53]:
b[b>25] = 0
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [54]:
b[b==0]=100
b

array([[100,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100]])

In [57]:
d = np.arange(36)
d.resize(6,6)
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [59]:
d.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [64]:
d[2:4,2:4]

array([[14, 15],
       [20, 21]])